# Generated by Django 4.2.30 on 2026-04-29 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_truckstop_id', models.IntegerField(help_text='OPIS Truckstop ID from the CSV data', unique=True)),
                ('name', models.CharField(help_text='Truckstop Name', max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('rack_id', models.IntegerField(help_text='Rack ID')),
                ('retail_price', models.DecimalField(decimal_places=3, help_text='Retail Price', max_digits=8)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fuel_station',
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='idx_station_lat_lon'), models.Index(fields=['state'], name='idx_station_state')],
            },
        ),
    ]
